**

!business-app-sii/
!business-app-sii/package.json
!business-app-sii/pnpm-lock.yaml
!business-app-sii/pnpm-workspace.yaml
!business-app-sii/nest-cli.json
!business-app-sii/tsconfig.json
!business-app-sii/tsconfig.build.json
!business-app-sii/src/
!business-app-sii/src/**
!business-app-sii/test/
!business-app-sii/test/**
!business-app-sii/scripts/
!business-app-sii/scripts/**
!business-app-sii/public/
!business-app-sii/public/**
!business-app-sii/docker/
!business-app-sii/docker/**

!sii-engine/
!sii-engine/package.json
!sii-engine/tsconfig.json
!sii-engine/tsconfig.build.json
!sii-engine/tsup.config.ts
!sii-engine/src/
!sii-engine/src/**
!sii-engine/test/
!sii-engine/test/**

**/.git
**/node_modules
**/dist
business-app-sii/.env*
business-app-sii/.ministack
business-app-sii/secure
business-app-sii/secrets
